### ISSUE TITLE
How to apply markdown-it-toc-and-anchor?

### ISSUE THREAD

**Issue by Explorare** [pujiaxun/pujiaxun.github.io#1]
I've read your [article ](http://www.pujiaxun.com/2016/08/12/20/) but still have no idea on how to make it works.

I've install the plugin on blog root

```
{ Blog }  » npm install markdown-it-toc-and-anchor --save
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
hexo-site@0.0.0 C:\Users\Explorare\Dropbox\Blog
└─┬ markdown-it-toc-and-anchor@4.1.1
  ├── clone@1.0.2
  └─┬ uslug@1.0.4
    └── unorm@1.4.1
```

And add `parser.use(require('markdown-it-named-headings'))` like your demo. But I don't know how to config it. (Such a noob X P) And I tried to excuse `hexo s` but get a bunch of errors:

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Cannot find module 'markdown-it-named-headings'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Hexo.module.exports (C:\Users\Explorare\Dropbox\Blog\node_modules\hexo-renderer-markdown-it\lib\renderer.js:11:14)
    at Hexo.tryCatcher (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\util.js:26:23)
    at Hexo.<anonymous> (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\method.js:15:34)
    at C:\Users\Explorare\Dropbox\Blog\node_modules\hexo\lib\hexo\render.js:51:21
    at tryCatcher (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\promise.js:245:10)
    at Async._drainQueue (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Explorare\Dropbox\Blog\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

It seems that the plugin doesn't been imported correctly?
What I want to achieve is just like this [page](https://hexo.io/docs/plugins.html#Publishing). A hidden permalink symbol on the right side next to he heading. And TOC support. 
Any suggestion?

**Comment by pujiaxun** [comment]
Wow, eh... I'm so sorry I didn't get any notifications about this issue.
Still in trouble there?
If not, I'll close it.

**Comment by Explorare** [comment]
Problem exists.
```
{ Blog } master » npm update                   /cygdrive/c/Users/Explorare/Dropbox/Blog
{ Blog } master » npm install markdown-it-toc-and-anchor --save
hexo-site@0.0.0 C:\Users\Explorare\Dropbox\Blog
`-- markdown-it-toc-and-anchor@4.1.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\hexo-generator-feed\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
{ Blog } master » npm version                  /cygdrive/c/Users/Explorare/Dropbox/Blog
{ 'hexo-site': '0.0.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.11.0',
  openssl: '1.0.2k',
  uv: '1.11.0',
  v8: '5.1.281.102',
  zlib: '1.2.11' }
```

**Comment by pujiaxun** [comment]
I removed node_modules and reinstalled it just now.

And followed my article, then got it.

The "markdown-it-named-headings" is what I talked about. I don't remember whether I tried markdown-it-toc-and-anchor as you said.

So, just `npm i -S markdown-it-named-headings` and follow my article.

FYI, this is my package.json

```json
{
  "name": "Jason-Blog",
  "version": "1.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.7"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.1.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.1.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.1.1",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-server": "^0.1.3",
    "markdown-it-named-headings": "^1.1.0"
  }
}
```

And the renderer.js (**node_modules/hexo-renderer-markdown-it/lib/renderer.js**)
```js
'use strict';

module.exports = function (data, options) {
  var MdIt = require('markdown-it');
  var cfg = this.config.markdown;
  var opt = (cfg) ? cfg : 'default';
  var parser = (opt === 'default' || opt === 'commonmark' || opt === 'zero') ?
    new MdIt(opt) :
    new MdIt(opt.render);

    // This line is the key
    parser.use(require('markdown-it-named-headings'));

  if (opt.plugins) {
    parser = opt.plugins.reduce(function (parser, pugs) {
      return parser.use(require(pugs));
    }, parser);
  }

  if (opt.anchors) {
    parser = parser.use(require('./anchors'), opt.anchors);
  }

  return parser.render(data.text);
};
```
